#BIOIMAGESUITE_LICENSE  ---------------------------------------------------------------------------------
#BIOIMAGESUITE_LICENSE  This file is part of the BioImage Suite Software Package.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  X. Papademetris, M. Jackowski, N. Rajeevan, H. Okuda, R.T. Constable, and L.H
#BIOIMAGESUITE_LICENSE  Staib. BioImage Suite: An integrated medical image analysis suite, Section
#BIOIMAGESUITE_LICENSE  of Bioimaging Sciences, Dept. of Diagnostic Radiology, Yale School of
#BIOIMAGESUITE_LICENSE  Medicine, http:#www.bioimagesuite.org.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is free software; you can redistribute it and/or
#BIOIMAGESUITE_LICENSE  modify it under the terms of the GNU General Public License version 2
#BIOIMAGESUITE_LICENSE  as published by the Free Software Foundation.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is distributed in the hope that it will be useful,
#BIOIMAGESUITE_LICENSE  but WITHOUT ANY WARRANTY; without even the implied warranty of
#BIOIMAGESUITE_LICENSE  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#BIOIMAGESUITE_LICENSE  GNU General Public License for more details.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  You should have received a copy of the GNU General Public License
#BIOIMAGESUITE_LICENSE  along with this program; if not, write to the Free Software
#BIOIMAGESUITE_LICENSE  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#BIOIMAGESUITE_LICENSE  See also  http:#www.gnu.org/licenses/gpl.html
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  If this software is modified please retain this statement and add a notice
#BIOIMAGESUITE_LICENSE  that it had been modified (and by whom).  
#BIOIMAGESUITE_LICENSE 
#BIOIMAGESUITE_LICENSE  -----------------------------------------------------------------------------------

# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or




# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# 	$Id: pkgIndex.tcl,v 1.2 2004/02/26 21:29:59 xenios Exp xenios $	


# -------------------------------------------------------
# Itcl stuff -- new versions of everything
# -------------------------------------------------------
package ifneeded pxitclsubjectentry  1.0 [list source [file join $dir pxitclsubjectentry.tcl]] 
package ifneeded pxitcllistselector  1.0 [list source [file join $dir pxitcllistselector.tcl]] 

package ifneeded pxitclbasecontrol 1.0 [list source [file join $dir pxitclbasecontrol.tcl]] 
package ifneeded pxitclbaseimagecontrol 1.0 [list source [file join $dir pxitclbaseimagecontrol.tcl]] 
package ifneeded pxitclbaseimageviewer 1.0 [list source [file join $dir pxitclbaseimageviewer.tcl]]
package ifneeded pxitcloverlaytool 1.0 [ list source [file join $dir pxitcloverlaytool.tcl]]

package ifneeded pxitclfilelistmenu 1.0 [list source [file join $dir pxitclfilelistmenu.tcl]]
package ifneeded pxitclHistogramWidget 1.0 [ list source [ file join $dir pxitclHistogramWidget.tcl ]]
package ifneeded pxitclLandmarkControl 1.0 [ list source [ file join $dir pxitclLandmarkControl.tcl ]]
package ifneeded pxitclPolyDataControl 1.0 [ list source [ file join $dir pxitclPolyDataControl.tcl ]]
package ifneeded pxitclElectrodeMultiControl 1.0 [ list source [ file join $dir pxitclElectrodeMultiControl.tcl ]]

package ifneeded pxitclimagenormalization 1.0 [ list source [ file join $dir pxitclimagenormalization.tcl ]]
package ifneeded pxitclimageimport 1.0 [ list source [ file join $dir pxitclimageimport.tcl ]]

package ifneeded pxitclatlasgadget   1.0 [list source [file join $dir pxitclatlasgadget.tcl]] 
package ifneeded pxitclwfuatlasgadget   1.0 [list source [file join $dir pxitclwfuatlasgadget.tcl]] 
package ifneeded pxitclyaleatlasgadget   1.0 [list source [file join $dir pxitclyaleatlasgadget.tcl]] 
package ifneeded pxitclanimationgadget   1.0 [list source [file join $dir pxitclanimationgadget.tcl]] 
package ifneeded pxitcldistributiontablegadget   1.0 [list source [file join $dir pxitcldistributiontablegadget.tcl]] 
package ifneeded pxitclbrainstrip    1.1 [list source [file join $dir pxitclbrainstrip.tcl]] 
package ifneeded pxitclexpfit        1.0 [list source [file join $dir pxitclexpfit.tcl]] 
package ifneeded pxitclcsigadget 1.0 [ list source [ file join $dir pxitclcsigadget.tcl ]] 
package ifneeded pxitclvvlinkgadget 1.0 [ list source [ file join $dir pxitclvvlinkgadget.tcl ]]
package ifneeded pxitclvvlinkprojectorgadget 1.0 [ list source [ file join $dir pxitclvvlinkprojectorgadget.tcl ]]
package ifneeded pxitclopenigtlinkgadget 1.0 [ list source [ file join $dir pxitclopenigtlinkgadget.tcl ]]
package ifneeded pxitclsplineobjectmap 1.0 [ list source [ file join $dir pxitclsplineobjectmap.tcl ]]
package ifneeded pxitclsplinestackobjectmap 1.0 [ list source [ file join $dir pxitclsplinestackobjectmap.tcl ]]
package ifneeded pxitclcreatesolidcontrol 1.0 [ list source [ file join $dir pxitclcreatesolidcontrol.tcl ]]

package ifneeded pxitclmultisubjectaverage 1.0 [ list source [ file join $dir pxitclmultisubjectaverage.tcl ]]

package ifneeded pxitclrpm  1.0 [list source [file join $dir pxitclrpm.tcl]] 
package ifneeded pxitclarticulatedmodel  1.0 [list source [file join $dir pxitclarticulatedmodel.tcl]] 
package ifneeded pxitclsurfaceobjectmap  1.0 [list source [file join $dir pxitclsurfaceobjectmap.tcl]] 
package ifneeded pxitclmanualsurfacetransformation  1.0 [list source [file join $dir pxitclmanualsurfacetransformation.tcl]] 
package ifneeded pxitclmousechopper  1.0 [list source [file join $dir pxitclmousechopper.tcl]] 
package ifneeded pxitclmeshgen  1.0 [list source [file join $dir pxitclmeshgen.tcl]] 
package ifneeded pxitclsurobj  1.0 [list source [file join $dir pxitclsurfaceobjectmap.tcl]] 
package ifneeded bis_fmrisetup  1.0 [list source [file join $dir bis_fmrisetup.tcl]] 
package ifneeded bis_fmri  1.0 [list source [file join $dir bis_fmri.tcl]] 
package ifneeded bis_databasetool  1.0 [list source [file join $dir bis_databasetool.tcl]] 
package ifneeded bis_realtimefmri  1.0 [list source [file join $dir bis_realtimefmri.tcl]]
package ifneeded bis_parameterGUI  1.0 [list source [file join $dir bis_algorithmdatabaseGUI.tcl]]


# ---------------------------------------------------------
# Major Viewers
# ---------------------------------------------------------
package ifneeded pxitclbaseimageviewer  1.0 [list source [file join $dir pxitclbaseimageviewer.tcl]] 
package ifneeded pxitclsurfaceeditor  1.0 [list source [file join $dir pxitclsurfaceeditor.tcl]] 
package ifneeded pxitclbrainregister  1.0 [list source [file join $dir pxitclbrainregister.tcl]] 
package ifneeded pxitclmouseregister  1.0 [list source [file join $dir pxitclmouseregister.tcl]] 
package ifneeded pxitclbase4dimageviewer  1.0 [list source [file join $dir pxitclbase4dimageviewer.tcl]] 
package ifneeded pxitclelectrodeeditor  1.0 [list source [file join $dir pxitclelectrodeeditor.tcl]] 

package ifneeded pxitclmanualtransformation 1.0 [ list source [ file join $dir pxitclmanualtransformation.tcl ]]
package ifneeded alarkutility 1.0 [list source [file join $dir alarkutility.tcl]]

