#BIOIMAGESUITE_LICENSE  ---------------------------------------------------------------------------------
#BIOIMAGESUITE_LICENSE  This file is part of the BioImage Suite Software Package.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  X. Papademetris, M. Jackowski, N. Rajeevan, H. Okuda, R.T. Constable, and L.H
#BIOIMAGESUITE_LICENSE  Staib. BioImage Suite: An integrated medical image analysis suite, Section
#BIOIMAGESUITE_LICENSE  of Bioimaging Sciences, Dept. of Diagnostic Radiology, Yale School of
#BIOIMAGESUITE_LICENSE  Medicine, http:#www.bioimagesuite.org.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is free software; you can redistribute it and/or
#BIOIMAGESUITE_LICENSE  modify it under the terms of the GNU General Public License version 2
#BIOIMAGESUITE_LICENSE  as published by the Free Software Foundation.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is distributed in the hope that it will be useful,
#BIOIMAGESUITE_LICENSE  but WITHOUT ANY WARRANTY; without even the implied warranty of
#BIOIMAGESUITE_LICENSE  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#BIOIMAGESUITE_LICENSE  GNU General Public License for more details.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  You should have received a copy of the GNU General Public License
#BIOIMAGESUITE_LICENSE  along with this program; if not, write to the Free Software
#BIOIMAGESUITE_LICENSE  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#BIOIMAGESUITE_LICENSE  See also  http:#www.gnu.org/licenses/gpl.html
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  If this software is modified please retain this statement and add a notice
#BIOIMAGESUITE_LICENSE  that it had been modified (and by whom).  
#BIOIMAGESUITE_LICENSE 
#BIOIMAGESUITE_LICENSE  -----------------------------------------------------------------------------------

# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

# 	$Id: pkgIndex.tcl,v 1.1 2002/02/20 18:07:50 Xenios Exp $	


# -------------------------------------------------------
# Itcl stuff -- new versions of everything
# -------------------------------------------------------
#This is the oldest version
package ifneeded pxitclbraintreegadget 1.0 [ list source [ file join $dir pxitclbraintreegadget.tcl ]]
package ifneeded chellyGUI_old 1.0 	[list source /mnt/cluster1/mdistasio/UIproject/JMainTest.tcl]

#Here is the stable version
package ifneeded pxitclsurgerythingy 1.0 [ list source [ file join $dir pxitclsurgerythingy.tcl ]]
package ifneeded chellyGUI 1.0  	 [ list source [ file join $dir ChellyGUI.tcl ]]

#This is the test version
package ifneeded pxitclsurgeryexperimental 1.0 \
    [ list source [ file join $dir pxitclsurgeryexperimental.tcl ]]
package ifneeded chellyGUI_2 1.0 \
    [list source [ file join $dir ChellyGUI_exp.tcl ]]

package ifneeded pxitclchellypackages 1.0 \
    [list source [ file join $dir [ file join packages pxitclchellypackages.tcl ]] ]

package ifneeded dsitcltree      1.0 [list source [ file join $dir dsitcltree.tcl      ]] 
package ifneeded bis_treegui     1.0 [list source [ file join $dir bis_treegui.tcl     ]] 
package ifneeded bis_treeguibase 1.0 [list source [ file join $dir bis_treeguibase.tcl ]] 
package ifneeded bis_nodeinfobox 1.0 [list source [ file join $dir bis_nodeinfobox.tcl ]] 
