#!/bin/bash


# --------------------------------------------------------------------------------------
# This file is part of the BioImage Suite Software Package. (seee www.bioimagesuite.org)
# --------------------------------------------------------------------------------------

#bis_fix_script_begin
BASE=/Users/mjack/src3/bioimagesuite30_src
#bis_fixscript_end

# ----------------------------------
# BIOIMAGESUITE: No edits below here
# ----------------------------------

source ${BASE}/setpaths.sh
bis.tcl


