#BIOIMAGESUITE_LICENSE  ---------------------------------------------------------------------------------
#BIOIMAGESUITE_LICENSE  This file is part of the BioImage Suite Software Package.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  X. Papademetris, M. Jackowski, N. Rajeevan, H. Okuda, R.T. Constable, and L.H
#BIOIMAGESUITE_LICENSE  Staib. BioImage Suite: An integrated medical image analysis suite, Section
#BIOIMAGESUITE_LICENSE  of Bioimaging Sciences, Dept. of Diagnostic Radiology, Yale School of
#BIOIMAGESUITE_LICENSE  Medicine, http:#www.bioimagesuite.org.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is free software; you can redistribute it and/or
#BIOIMAGESUITE_LICENSE  modify it under the terms of the GNU General Public License version 2
#BIOIMAGESUITE_LICENSE  as published by the Free Software Foundation.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is distributed in the hope that it will be useful,
#BIOIMAGESUITE_LICENSE  but WITHOUT ANY WARRANTY; without even the implied warranty of
#BIOIMAGESUITE_LICENSE  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#BIOIMAGESUITE_LICENSE  GNU General Public License for more details.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  You should have received a copy of the GNU General Public License
#BIOIMAGESUITE_LICENSE  along with this program; if not, write to the Free Software
#BIOIMAGESUITE_LICENSE  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#BIOIMAGESUITE_LICENSE  See also  http:#www.gnu.org/licenses/gpl.html
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  If this software is modified please retain this statement and add a notice
#BIOIMAGESUITE_LICENSE  that it had been modified (and by whom).  
#BIOIMAGESUITE_LICENSE 
#BIOIMAGESUITE_LICENSE  -----------------------------------------------------------------------------------

# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or




# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded labelframe 1.0 [list source [file join $dir labelframe.tcl]]
package ifneeded feedbackplus 1.0 [list source [file join $dir feedbackplus.tcl]]
package ifneeded pxtclbrukerheader 1.0 [list source [file join $dir pxtclbrukerheader.tcl]]
package ifneeded pxtclhelp 1.0 [list source [file join $dir pxtclhelp.tcl]]
package ifneeded pxtclreadsprheader 1.0 [list source [file join $dir pxtclreadsprheader.tcl]]
package ifneeded pxtclreadvarianheader 1.0 [list source [file join $dir pxtclreadvarianheader.tcl]]

package ifneeded pxtcluserprefs 1.0 [list source [file join $dir pxtcluserprefs.tcl]]
package ifneeded pxtclutil 1.0 [list source [file join $dir pxtclutil.tcl]]
package ifneeded pxvtable 1.0 [list source [file join $dir pxvtable.tcl]]
package ifneeded pxtclruncommand 1.0 [list source [file join $dir pxtclruncommand.tcl]]
package ifneeded vtkImageInclude 1.0 [list source [file join $dir vtkImageInclude.tcl]]
package ifneeded vtkpxcontrib 1.2 [list source [file join $dir vtkpxcontrib.tcl]]
package ifneeded biscmdline 1.0 [list source [file join $dir biscmdline.tcl]]
package ifneeded vtknrcontrib 1.1 [list source [file join $dir vtknrcontrib.tcl]]
package ifneeded vtkfemlib 1.0 [list source [file join $dir vtkfemlib.tcl]]
package ifneeded VisTree 3.0   [list source [file join $dir VisTree3.tcl]]


# Core Objects moved here from main
# ----------------------------------
package ifneeded pxitclobject         1.0 [list source [file join $dir pxitclobject.tcl]] 
package ifneeded pxitclimage         1.0 [list source [file join $dir pxitclimage.tcl]] 
package ifneeded pxitclsurface         1.0 [list source [file join $dir pxitclsurface.tcl]] 
package ifneeded pxitcllandmarks         1.0 [list source [file join $dir pxitcllandmarks.tcl]] 
package ifneeded pxitclelectrodemultigrid         1.0 [list source [file join $dir pxitclelectrodemultigrid.tcl]] 
package ifneeded pxitcltransform     1.0 [list source [file join $dir pxitcltransform.tcl]] 
package ifneeded pxitclmesh         1.0 [list source [file join $dir pxitclmesh.tcl]] 
package ifneeded pxitclcamera     1.0 [list source [file join $dir pxitclcamera.tcl]] 



