#BIOIMAGESUITE_LICENSE  ---------------------------------------------------------------------------------
#BIOIMAGESUITE_LICENSE  This file is part of the BioImage Suite Software Package.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  X. Papademetris, M. Jackowski, N. Rajeevan, H. Okuda, R.T. Constable, and L.H
#BIOIMAGESUITE_LICENSE  Staib. BioImage Suite: An integrated medical image analysis suite, Section
#BIOIMAGESUITE_LICENSE  of Bioimaging Sciences, Dept. of Diagnostic Radiology, Yale School of
#BIOIMAGESUITE_LICENSE  Medicine, http:#www.bioimagesuite.org.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is free software; you can redistribute it and/or
#BIOIMAGESUITE_LICENSE  modify it under the terms of the GNU General Public License version 2
#BIOIMAGESUITE_LICENSE  as published by the Free Software Foundation.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  This program is distributed in the hope that it will be useful,
#BIOIMAGESUITE_LICENSE  but WITHOUT ANY WARRANTY; without even the implied warranty of
#BIOIMAGESUITE_LICENSE  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#BIOIMAGESUITE_LICENSE  GNU General Public License for more details.
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  You should have received a copy of the GNU General Public License
#BIOIMAGESUITE_LICENSE  along with this program; if not, write to the Free Software
#BIOIMAGESUITE_LICENSE  Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
#BIOIMAGESUITE_LICENSE  See also  http:#www.gnu.org/licenses/gpl.html
#BIOIMAGESUITE_LICENSE  
#BIOIMAGESUITE_LICENSE  If this software is modified please retain this statement and add a notice
#BIOIMAGESUITE_LICENSE  that it had been modified (and by whom).  
#BIOIMAGESUITE_LICENSE 
#BIOIMAGESUITE_LICENSE  -----------------------------------------------------------------------------------

# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

#my chellyDB package
package ifneeded chellyDB 1.0 [list source [file join $dir chellyDB.tcl]]
package ifneeded pxitclchellypackages 1.0 [list source [file join $dir pxitclchellypackages.tcl]]


#my VisTree package
package ifneeded VisTree      1.0 [list source [file join $dir VisTree.tcl]];#obsolete
package ifneeded VisTree2      2.0 [list source [file join $dir VisTree2.tcl]]

#my modified OverlayTool package
package ifneeded pxitcloverlaytab 1.0 [list source [file join $dir pxitcloverlaytab.tcl]]

#struct packages
if {![package vsatisfies [package provide Tcl] 8.2]} {return}
package ifneeded struct            2.1   [list source [file join $dir struct.tcl]]
package ifneeded struct            1.4   [list source [file join $dir struct1.tcl]]

package ifneeded struct::graph     2.0   [list source [file join $dir graph.tcl]]
package ifneeded struct::queue     1.3   [list source [file join $dir queue.tcl]]
package ifneeded struct::stack     1.3   [list source [file join $dir stack.tcl]]
package ifneeded struct::tree      2.0   [list source [file join $dir tree.tcl]]
package ifneeded struct::matrix    2.0   [list source [file join $dir matrix.tcl]]
package ifneeded struct::pool      1.2.1 [list source [file join $dir pool.tcl]]
package ifneeded struct::record    1.2.1 [list source [file join $dir record.tcl]]
package ifneeded struct::list      1.4   [list source [file join $dir list.tcl]]
package ifneeded struct::set       2.1   [list source [file join $dir sets.tcl]]
package ifneeded struct::prioqueue 1.3   [list source [file join $dir prioqueue.tcl]]
package ifneeded struct::skiplist  1.3   [list source [file join $dir skiplist.tcl]]

package ifneeded struct::graph     1.2.1 [list source [file join $dir graph1.tcl]]
package ifneeded struct::matrix    1.2.1 [list source [file join $dir matrix1.tcl]]


#my AtlasProg package
package ifneeded AtlasProg 1.0 [list source [file join $dir AtlasProg.tcl]]

#my SPECT Processing  package
package ifneeded SPECTProcessProg 1.0 [list source [file join $dir SPECTtools.tcl]]

#my ElectrodeAttrProg package
package ifneeded ElectrodeAttrProg 1.0 [list source [file join $dir ElectrodeAttrProg.tcl]]

#my ElectrodeAttrProg package
package ifneeded mdImageUtils 1.0 [list source [file join $dir mdImageUtils.tcl]]

#The Advanced Reg Tools  package
package ifneeded AdvancedRegTools 1.0 [list source [file join $dir AdvancedRegTools.tcl]]

